### ISSUE TITLE
Query ending: end() vs execute()

### ISSUE THREAD

**Issue by m-kus** [supabase/postgrest-dart#12]
Hey guys, great job with the postgrest libraries!
I wonder what is the rationale behing choosing `end()` as the query ending instead of `execute()` which is already used in your Rust and Python libraries?  
I think it makes more sense in a consistent syntax so that all the tutorials/examples are reusable for each new language supported.

**Comment by phamhieu** [comment]
I choose `end()` because it's the shortest verb I can think of to complete the query chain.

`a consistent syntax so that all the tutorials/examples are reusable for each new language supported.`
It's a good point. Thanks @m-kus! I don't mind using `execute()` to have a consistent syntax. 

What do you think? @kiwicopple

**Comment by kiwicopple** [comment]
> a consistent syntax so that all the tutorials/examples are reusable for each new language supported.

100% on board with this.

It isn't actually required for JS, since the Promise is implicitly returned from the `await`, but for everything else we should try to map the syntax 1:1. It will be great if we can produce an reference docs which are consistent across all languages
